- name: Include VPN credentials
  include_vars:
    file: ../vars/credentials.yml

- name: install keycloak prerequisites
  yum: 
    name: ["java",'firewalld'] 
    state: present
  when: init

- name: Keycloak user
  user: 
    name: keycloak
  when: init or start

- name: keycloak target directory
  file: 
    dest: "{{ keycloak_dir }}"
    mode: 0755
    owner: root
    group: root
    state: directory
  when: init

- name: get Keycloak distribution tarball
  get_url: 
    url: "{{ keycloak_url }}"
    dest: "{{ keycloak_dir }}"
  when: init

- name: unpack keycloak
  unarchive: 
    src: "{{ keycloak_dir }}/keycloak-{{ keycloak_version }}.tar.gz"
    dest: "{{ keycloak_dir }}"
    copy: no
  when: init


- name: keycloak data directory
  file: 
    dest: "{{ keycloak_home }}/standalone"
    mode: 0775
    owner: keycloak
    group: keycloak
    state: directory
    recurse: yes
  when: init or start


- name: keycloak systemd setup
  template:
    owner: root 
    group: root 
    mode: 0644
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
  notify:
    - reload systemd
  when: init or start

- name: Open Firewall for services
  firewalld: 
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - 8080/tcp
    - 9990/tcp
  when: init or start

- name: keycloak systemd service enable and start
  service: 
    name: keycloak
    enabled: yes
    state: started

