---
- hosts: picard
  connection: local
  tasks:
    - name: Include VPN credentials
      tags:
        - download_hub
      include_vars:
        file: group_vars/credentials.yml

######################################################################################
#                                 Create Folders                                     #
######################################################################################
    - name: plex tasks
      import_tasks: tasks/plex.yml
      tags: plex

    - name: radius tasks
      import_tasks: tasks/radius.yml
      tags: radius

    - name: download_hub tasks
      import_tasks: tasks/download-hub.yml
      tags: download_hub

    - name: gitea tasks
      import_tasks: tasks/gitea.yml
      tags: gitea

    - name: nextcloud tasks
      import_tasks: tasks/nextcloud.yml
      tags: nextcloud

    - name: sonarr/radarr/lidarr/jackett tasks
      import_tasks: tasks/rrs.yml
      tags: 
       - lidarr
       - sonarr
       - radarr
       - jackett
       - rrs
######################################################################################
#                                 Docker Networks                                    #
######################################################################################
    - name: Docker main network
      tags:
        - networks
      docker_network:
        name: main
        driver: bridge
        driver_options:
          com.docker.network.bridge.name: "docker1"
        ipam_config:
          - subnet: 172.16.100.0/26
            gateway: 172.16.100.1
#    - name: Docker stats network
#      tags:
#        - networks
#      docker_network:
#        name: stats
#        driver: bridge
#        driver_options:
#          com.docker.network.bridge.name: "docker2"
#        ipam_config:
#          - subnet: 172.16.1.0/27
#            gateway: 172.16.1.1
    - name: Docker torrent network
      tags:
        - networks
      docker_network:
        name: torrent
        driver: bridge
        driver_options:
          com.docker.network.bridge.name: "docker3"
        ipam_config:
          - subnet: 172.16.2.0/27
            gateway: 172.16.2.1
    - name: Docker nginx isolation network
      tags:
        - networks
        - nginx
      docker_network:
        name: nginx
        driver: bridge
        driver_options: 
          com.docker.network.bridge.name: "docker4"
        ipam_config:
          - subnet: 172.16.200.0/28
            gateway: 172.16.200.1
      

######################################################################################
#                                 Docker Containers                                  #
######################################################################################
#
#
#
#
#######################################################
###################### Plex ###########################
#######################################################
    - name: plex Docker Container
      tags:
        - plex
      docker_container:
        name: plex
        image: linuxserver/plex
        pull: true
        volumes:
          - "{{ plex_config }}:/config:rw"
          - "{{ plex_library }}/Movies:/movies:rw"
          - "{{ plex_library }}/TV\ Shows:/tv:rw"
          - "{{ plex_library }}/Music:/music:ro"
          - "{{ plex_library }}/Other:/other:ro"
        network_mode: "host"
        env:
          TZ: "{{ timezone }}"
          VERSION: "docker"
          PUID: "1000"
          PGID: "1000"
        restart_policy: unless-stopped
        memory: 1g
        cpu_period: 100000
        cpu_quota: 100000
#######################################################
###################### NGINX ##########################
#######################################################
    - name: NGINX Docker Container
      tags:
        - nginx
      docker_container:
        name: nginx
        image: nginx:latest
        pull: true
        volumes:
          - "/var/www/html:/var/www/html:ro"
          - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
          - "/etc/nginx/sites-available/nrichman.dev:/etc/nginx/sites-enabled/nrichman.dev"
            #- "/etc/nginx/modules-enabled-docker:/etc/nginx/modules-enabled"
          - "/etc/ssl/nrichman.dev:/etc/ssl/nrichman.dev:ro"
            #- "/usr/share/nginx/modules:/etc/nginx/modules:ro"
          - "/var/log/nginx:/var/log/nginx:rw"
        ports:
          - "80:80"
          - "443:443"
        networks:
          - name: nginx
            ipv4_address: "172.16.200.2"
            aliases:
              - "nginx"
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        memory: 1g
        cpu_period: 100000
        cpu_quota: 25000
#######################################################
################### download_hub ######################
#######################################################
    - name: download_hub with VPN
      tags:
        - download_hub
      docker_container:
        name: download_hub
        image: nrichman/download-hub
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/etc/timezone:/etc/timezone:ro"
          - "{{ download_hub }}/transmission_config:/config:rw"
          - "{{ download_hub }}/Downloads/transmission:/storage/downloads:rw"
          - "{{ download_hub }}/soulseek_appdata:/root/.SoulseekQt"
          - "{{ download_hub }}/soulseek_logs:/root/Soulseek Chat Logs"
          - "{{ download_hub }}/Downloads/soulseek:/root/Soulseek Downloads"
          - "{{ download_hub }}/Downloads/deezloader:/downloads"
          - "{{ download_hub }}/deezloader_config:/root/.config/Deezloader Remix/config"
          - "{{ plex_library }}:/root/Library:ro"
        ports:
          - "9091:9091/tcp"
          - "9091:9091/udp"
          - "6080:6080"
          - "1730:1730"
        networks:
          - name: torrent
            ipv4_address: "172.16.2.2"
            aliases:
              - "download_hub"
        networks_cli_compatible: yes
        env:
          TRANSMISSION_HOME: /config
          TRANSMISSION_DOWNLOAD_DIR: /storage/downloads/complete
          TRANSMISSION_INCOMPLETE_DIR: /storage/downloads/incomplete
          TRANSMISSION_WATCH_DIR: /storage/watch
          OPENVPN_PROVIDER: "{{ vpn_provider }}"
          OPENVPN_USERNAME: "{{ vpn_username }}"
          OPENVPN_PASSWORD: "{{ vpn_password }}"
          OPENVPN_CONFIG: "{{ vpn_config }}"
          OPENVPN_OPTS: "--redirect-gateway def1 --mssfix 1450"
          PUID: "0"
          PGID: "0"
          LOCAL_NETWORK: "{{ transmission_local_network }}"
          ENABLE_UFW: "false"
          CREATE_TUN_DEVICE: "true"
          TRANSMISSION_RPC_USERNAME: "{{ transmission_username }}"
          TRANSMISSION_RPC_PASSWORD: "{{ transmission_password }}"
        capabilities:
          - NET_ADMIN
        restart_policy: unless-stopped
        memory: 1g
        cpu_period: 100000
        cpu_quota: 50000
#######################################################
####################### Gitea #########################
#######################################################
    - name: Gitea docker image
      docker_container:
        name: gitea
        image: gitea/gitea
        pull: true
        hostname: git.nrichman.dev
        volumes:
          - "{{ gitea }}:/data:rw"
        ports:
          - "28000:3000"
        networks:
          - name: main
            ipv4_address: "172.16.100.2"
            aliases:
              - "git"
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        memory: 1g
#######################################################
#################### FreeRADIUS #######################
#######################################################
    - name: FreeRADIUS docker
      tags: radius
      docker_container:
        name: freeradius
        image: freeradius/freeradius-server:latest
        hostname: freeradius
        pull: true
        volumes:
          - "{{ freeradius }}:/etc/freeradius"
#        ports:
#          - "1812:1812/udp"
#          - "1813:1813/udp"
#        networks:
#          - name: main
#            ipv4_address: "172.16.100.5"
#            aliases:
#              - "freeradius"
#        networks_cli_compatible: yes
        restart_policy: unless-stopped
        memory: 1g 
        cpu_period: 100000
        cpu_quota: 15000
#######################################################
###################### MariaDB ########################
#######################################################
    - name: Mariadb docker
      docker_container:
        name: mariadb
        image: yobasystems/alpine-mariadb
        hostname: mariadb
        pull: true
        volumes:
          - "{{ mariadb }}:/var/lib/mysql"
        env:
          MYSQL_DATABASE: "blog"
          MYSQL_USER: "mysql"
          MYSQL_PASSWORD: "{{ mariadb_password }}"
          MYSQL_ROOT_PASSWORD: "{{ mariadb_password }}"
        ports:
          - "3306:3306"
        networks:
          - name: main
            ipv4_address: "172.16.100.3"
            aliases:
              - "mariadb"
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        memory: 1g 
        cpu_period: 100000
        cpu_quota: 15000
#######################################################
##################### Nextcloud #######################
#######################################################
    - name: Nextcloud Docker 
      docker_container:
        name: nextcloud
        image: nextcloud:latest
        pull: true
        volumes:
          - "{{ nextcloud }}/html:/var/www/html"
          - "{{ nextcloud }}/config:/var/www/html/config"
          - "{{ nextcloud }}/html:/var/www/html/data"
        env:
          MYSQL_DATABASE: "nextcloud"
          MYSQL_USER: "mysql"
          MYSQL_PASSWORD: "{{ mariadb_password }}"
          MYSQL_HOST: "172.17.0.2:3306"
          NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin }}"
          NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
          #NEXTCLOUD_TRUSTED_DOMAINS: "nrichman.dev www.nrichman.dev"
        ports:
          - "3005:80"
        networks:
          - name: main
            ipv4_address: "172.16.100.4"
            aliases:
              - "nextcloud"
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        memory: 1g 
        cpu_period: 100000
        cpu_quota: 50000
#######################################################
####################### Lidarr ########################
#######################################################
    - name: Lidarr
      tags:
        - lidarr
        - rrs
      docker_container:
        name: lidarr
        image: linuxserver/lidarr
        pull: true
        volumes:
          - "{{ download_hub }}/lidarr:/config"
          - "{{ download_hub }}/Downloads/transmission/complete:/storage/downloads/complete"
          - "{{ plex_library }}/Music:/music"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "America/Chicago"
        ports:
          - "3007:8686"
        networks:
          - name: torrent
            ipv4_address: "172.16.2.3"
            aliases:
              - "lidarr"
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        memory: 1g 
        cpu_period: 100000
        cpu_quota: 55000
#######################################################
####################### Radarr ########################
#######################################################
    - name: radarr container
      tags:
        - radarr
        - rrs
      docker_container:
        name: radarr
        image: linuxserver/radarr:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "3009:7878"
        networks:
          - name: torrent
            ipv4_address: "172.16.2.4"
            aliases:
              - "radarr"
        networks_cli_compatible: yes
        env:
          TZ: "America/Chicago"
          PGID: "1000"
          PUID: "1000"
        volumes:
          - "{{ plex_library }}/Movies:/movies"
          - "{{ download_hub }}/Downloads/transmission/complete:/downloads"
          - "{{ download_hub }}/radarr:/config"
        memory: 1g 
        cpu_period: 100000
        cpu_quota: 55000
#######################################################
####################### Sonarr ########################
#######################################################
    - name: sonarr container
      tags:
        - sonarr
        - rrs
      docker_container:
        name: sonarr
        image: linuxserver/sonarr
        state: started
        restart_policy: unless-stopped
        ports:
          - "3011:8989"
        networks:
          - name: torrent
            ipv4_address: "172.16.2.5"
            aliases:
              - "sonarr"
        networks_cli_compatible: yes
        env:
          TZ: "America/Chicago"
          PGID: "1000"
          PUID: "1000"
        volumes:
          - "{{ plex_library }}/TV\ Shows:/tv"
          - "{{ download_hub }}/Downloads/transmission/complete:/downloads"
          - "{{ download_hub }}/sonarr:/config"
        memory: 1g 
        cpu_period: 100000
        cpu_quota: 55000
#######################################################
###################### Jackett ########################
#######################################################
    - name: Jackett Container
      tags:
        - jackett
        - rrs
      docker_container:
        name: jackett
        image: linuxserver/jackett
        state: started
        restart_policy: unless-stopped
        ports:
          - "9117:9117"
        networks:
          - name: torrent
            ipv4_address: "172.16.2.6"
            aliases:
              - "jackett"
        networks_cli_compatible: yes
        env:
          TZ: "America/Chicago"
          PGID: "1000"
          PUID: "1000"
        volumes:
          - "{{ jackett }}:/config"
          - "{{ jackett_torrent_blackhole }}:/downloads"
    
