---
- hosts: server
  tasks:
######################################################################################
#                                 Create Folders                                     #
######################################################################################
    - name: stats tasks
      import_tasks: tasks/stats.yml
      tags: stats

######################################################################################
#                                 Docker Containers                                  #
######################################################################################
#
#
#
#
#######################################################
##################### Telegraf ########################
#######################################################
    - name: Telegraf docker
      docker_container:
        name: telegraf
        image: telegraf
        pull: true
        volumes:
          - "{{ telegraf }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
          - "161:161"
        networks:
          - name: stats
            ipv4_address: "172.16.1.3"
            aliases:
              - "telegraf"
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        memory: 1g
        cpu_period: 100000
        cpu_quota: 25000
