---
- name: Create NextCloud Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ download_hub }}/lidarr:/config"
    - "{{ download_hub }}/Downloads/lidarr:/downloads"
    - "{{ nextcloud }}/Downloads/lidarr/music:/music"
  become: yes
