---
- name: Create InfluxDB and Telegraf Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb }}"
    - "{{ telegraf }}"

- name: Create Grafana Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "472"
    recurse: yes
  with_items:
    - "{{ grafana }}"
    - "{{ grafana }}/data"
    - "{{ grafana }}/config/"
    - "{{ grafana }}/config/provisioning"
    - "{{ grafana }}/config/provisioning/datasources"
  become: yes

- name: InfluxDB
  docker_container:
    name: influxdb
    image: influxdb
    pull: true
    volumes:
      - "{{ influxdb }}:/var/lib/influxdb:rw"
    ports:
      - "8086:8086"
    restart_policy: unless-stopped
    env:
      INFLUXDB_LOGGING_LEVEL: "error"
    memory: 1g
    cpu_period: 100000
    cpu_quota: 25000

- name: Template telegraf.conf
  template:
    src: templates/telegraf.conf
    dest: "{{ telegraf }}/telegraf.conf"

- name: Telegraf docker
  docker_container:
    name: telegraf
    image: telegraf
    pull: true
    volumes:
      - "{{ telegraf }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 25000

- name: Template Grafana data source
  template:
    src: templates/grafana.yml
    dest: "{{ grafana }}/config/provisioning/datasources/{{ hostvars['localhost']['ansible_hostname'] }}.yml"

- name: Grafana docker
  docker_container:
    name: grafana
    image: grafana/grafana
    pull: true
    volumes:
      - "{{ grafana }}/data:/var/lib/grafana:rw"
      - "{{ grafana }}/config/provisioning:/etc/grafana/provisioning:ro"
    ports:
      - "3000:3000"
    env:
      GF_SERVER_ROOT_URL: "http://dashboard.nrichman.dev"
      GF_SECURITY_ADMIN_PASSWORD: "test"
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 25000
#    labels:
#      traefik.backend: "grafana"
#      traefik.frontend.rule: "Host:grafana.{{ ansible_nas_domain }}"
#      traefik.enable: "{{ grafana_available_externally }}"
#      traefik.port: "3000"
