---
- name: Create InfluxDB and Telegraf Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb }}/etc"
    - "{{ influxdb }}/var"
    - "{{ telegraf }}"

- name: Create Grafana Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "472"
    recurse: yes
  with_items:
    - "{{ grafana }}"
    - "{{ grafana }}/data"
    - "{{ grafana }}/config/"
    - "{{ grafana }}/config/provisioning"
    - "{{ grafana }}/config/provisioning/datasources"
  become: yes

- name: Template telegraf.conf
  template:
    src: ../templates/telegraf-master.conf
    dest: "{{ telegraf }}/telegraf.conf"

- name: Template Grafana data source
  template:
    src: ../templates/grafana.yml
    dest: "{{ grafana }}/config/provisioning/datasources/{{ ansible_facts['hostname'] }}.yml"
