---
- name: Include VPN credentials
  include_vars: group_vars/vpn_credentials.yml

- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission }}/config"
    - "{{ transmission }}/Downloads"
  become: yes

- name: Transmission with VPN
  docker_container:
    name: transmission-openvpn
    image: haugene/transmission-openvpn
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ transmission }}/config:/storage/downloads:rw"
      - "{{ transmission }}/Downloads:/config:rw"
        #- "{{ ovpn_conf }}:/openvpn:ro"
    ports:
      - "9091:9091"
      - "51413:51413"
    env:
      TRANSMISSION_HOME: /config
      TRANSMISSION_DOWNLOAD_DIR: /storage/downloads/complete
      TRANSMISSION_INCOMPLETE_DIR: /storage/downloads/incomplete
      TRANSMISSION_WATCH_DIR: /storage/watch
      OPENVPN_PROVIDER: "{{ vpn_provider }}"
      OPENVPN_USERNAME: "{{ vpn_username }}"
      OPENVPN_PASSWORD: "{{ vpn_password }}"
      # OPENVPN_CONFIG: "{{ vpn_config }}"
      OPENVPN_OPTS: "--redirect-gateway def1"
      PUID: "0"
      PGID: "0"
      LOCAL_NETWORK: "{{ transmission_local_network }}"
      ENABLE_UFW: "false"
      CREATE_TUN_DEVICE: "true"
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    memory: 1g
