#
#							               _ _           
#							 _ __ __ _  __| (_)_   _ ___ 
#							| '__/ _` |/ _` | | | | / __|
#							| | | (_| | (_| | | |_| \__ \
#							|_|  \__,_|\__,_|_|\__,_|___/
#                             
#
########################################################
################ Files and Directories #################
########################################################
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ freeradius  }}"
  become: yes

#- name: Template Grafana data source
#  template:
#    src: ../templates/grafana.j2
#    dest: "{{ grafana }}/config/provisioning/datasources/{{ influxdb_name }}.yml"
#  become: yes


########################################################
#################### Freeradius ########################
########################################################
- name: Freeradius docker
  docker_container:
    name: freeradius
    image: freeradius/freeradius-server
    pull: true
    volumes:
      - "{{ freeradius_config }}:/etc/raddb:ro"
    ports:
      - "1812-1813:1812-1813/udp"
    env:
    restart_policy: unless-stopped
    memory: 1g

########################################################
####################### MariaDB ########################
########################################################
- name: MariaDB
  docker_container:
    name: mariadb
    image: mariadb
    pull: true
    restart_policy: unless-stopped
    env:
      MYSQL_ROOT_PASSWORD: "{{ root_password }}"

########################################################
###################### Telegraf ########################
########################################################
- name: Include credentials
  include_vars:
    file: ../vars/credentials.yml
- name: Login to Docker Repo
  docker_login:
    username: "{{ docker_login }}"
    password: "{{ docker_passwd }}"

- name: Telegraf docker
  docker_container:
    name: telegraf
    image: nrichman2/telegraf_snmp:armhf #telegraf-snmp hash so it's not pulled
    volumes:
      - "{{ telegraf }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "161:161"
    restart_policy: unless-stopped
    memory: 1g
    dns_servers:
      - "{{ dns }}"
    cpu_period: 100000
    cpu_quota: 25000

- name: Log out of Docker Repo
  docker_login:
    state: absent

