---
  - hosts:
     - all
    tasks:
      - name: "Build hosts file"
        lineinfile: 
          dest: /etc/hosts 
          regexp: ".*{{ item }}$"
          line: "{{ hostvars[item]['ansible_host'] }} {{item}}"
          state: present
        with_items: "{{ groups['all'] }}"
        become: yes
