
- name: Include VPN credentials
  include_vars:
    file: ../vars/credentials.yml

- name: Create nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nextcloud }}/html"
    - "{{ nextcloud }}/config"
    - "{{ nextcloud }}/data"

  become: yes

#######################################################
##################### Nextcloud #######################
#######################################################
- name: Nextcloud Docker 
  docker_container:
    name: nextcloud
    image: nextcloud:latest
    pull: true
    volumes:
      - "{{ nextcloud }}/html:/var/www/html"
      - "{{ nextcloud }}/config:/var/www/html/config"
      - "{{ nextcloud }}/html:/var/www/html/data"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: '{{ mariadb_user }}'
      MYSQL_PASSWORD: "{{ mariadb_password }}"
      MYSQL_HOST: "172.16.100.1:3306"
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.nrichman.dev"
    ports:
      - "3005:80"
    networks:
      - name: main
        ipv4_address: "172.16.100.5"
        aliases:
          - "nextcloud"
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    memory: 1g 
    cpu_period: 100000
    cpu_quota: 50000
