- name: Include credentials
  include_vars:
    file: ../vars/credentials.yml
#######################################################
###################### MariaDB ########################
#######################################################
- name: Mariadb docker
  docker_container:
    name: mariadb
    image: yobasystems/alpine-mariadb
    hostname: mariadb
    pull: true
    volumes:
      - "{{ mariadb }}:/var/lib/mysql"
      - "{{ mariadb_cnf }}:/etc/my.cnf.d"
    ports:
      - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_password }}"
    networks:
      - name: main
        ipv4_address: "172.16.100.3"
        aliases:
          - "mariadb"
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    memory: 1g 
    cpu_period: 100000
    cpu_quota: 15000
