
- name: gitea tasks
  import_tasks: gitea.yml
  tags: gitea

#######################################################
####################### Gitea #########################
#######################################################
- name: Gitea docker image
  docker_container:
    name: gitea
    image: gitea/gitea
    pull: true
    hostname: git.nrichman.dev
    volumes:
      - "{{ gitea }}:/data:rw"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
    ports:
      - "28000:3000"
      - "28001:22"
    networks:
      - name: main
        ipv4_address: "172.16.100.2"
        aliases:
          - "git"
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    memory: 1g
