#Plex config
plex_config: /docker/plex
plex_library: /media/Library

airsonic_config: /docker/airsonic
airsonic_user: "airsonic"
airsonic_uid: 151

jellyfin_config: /docker/jellyfin
jellyfin_user: "jellyfin"
jellyfin_uid: 152


