---
- name: Create Download-Hub Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: downloads
  with_items:
    - "{{ download_hub }}/transmission_config"
    - "{{ download_hub }}/Downloads/transmission"
    - "{{ download_hub }}/Downloads/transmission_watch"
    - "{{ download_hub }}/soulseek_appdata"
    - "{{ download_hub }}/soulseek_logs"
    - "{{ download_hub }}/deezloader_config"
    - "{{ download_hub }}/Downloads/soulseek"
    - "{{ download_hub }}/Downloads/deezloader"
  become: yes

- name: Grant access to transmission files for library group
  acl:
    path: "{{ item }}"
    entity: library
    etype: group
    permissions: rwx
    state: present
  with_items:
    - "{{ download_hub }}/Downloads/transmission"
    - "{{ download_hub }}/Downloads/transmission_watch"
  become: yes


