- name: Include VPN credentials
  include_vars:
    file: /etc/ansible/roles/download_hub/vars/credentials.yml

- name: sonarr/radarr/lidarr/jackett tasks
  import_tasks: rrs.yml
  when: start or init

- name: docker torrent network
  docker_network:
    name: torrent
    driver: macvlan
    driver_options:
      com.docker.network.bridge.name: "docker2"
      parent: vlan99@enp2s0
    ipam_config:
      - subnet: 172.16.0.0/27
        gateway: 172.16.0.1
    state: present
    force: yes
  when: init

#######################################################
####################### Lidarr ########################
#######################################################
- name: Lidarr
  docker_container:
    name: lidarr
    image: linuxserver/lidarr:latest
    pull: true
    volumes:
      - "{{ lidarr }}:/config"
      - "{{ transmission_downloads }}/complete:/storage/downloads/complete"
      - "{{ library }}/Music:/music"
    etc_hosts: "{{ extra_hosts }}"
    env:
      PUID: "117"
      PGID: "995"
      TZ: "America/Chicago"
    ports:
      - "3007:8686"
    networks:
      - name: torrent
        ipv4_address: "172.16.0.3"
        aliases:
          - "lidarr"
    purge_networks: yes
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    memory: 1g 
    cpu_period: 100000
    cpu_quota: 30000
#######################################################
####################### Radarr ########################
#######################################################
- name: Template radarr autoProcess
  template:
    src: ../templates/autoProcess.ini.j2
    dest: "{{ radarr }}/sickbeard/autoProcess.ini"
    owner: radarr
    group: library
  vars:
    output: "{{radarr_output}}"
  become: yes

- name: radarr container
  docker_container:
    name: radarr
    image: mdhiggins/radarr-sma:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "3009:7878"
    networks:
      - name: torrent
        ipv4_address: "172.16.0.4"
        aliases:
          - "radarr"
    purge_networks: yes
    networks_cli_compatible: yes
    etc_hosts: "{{ extra_hosts }}"
    env:
      TZ: "America/Chicago"
      PUID: "116"
      PGID: "996"
    volumes:
      - "{{ library }}/Movies:/movies"
      - "{{ transmission_downloads }}/complete:/downloads"
      - "{{ radarr }}:/config:rw"
      - "{{ radarr }}/sickbeard:/usr/local/sma/config"
    memory: 1g 
    cpu_period: 100000
    cpu_quota: 30000
#######################################################
####################### Sonarr ########################
#######################################################
- name: Template sonarr autoProcess
  template:
    src: ../templates/autoProcess.ini.j2
    dest: "{{ sonarr }}/sickbeard/autoProcess.ini"
    owner: sonarr
    group: library
  vars:
    output: "{{sonarr_output}}"
  become: yes

- name: sonarr container
  docker_container:
    name: sonarr
    image: mdhiggins/sonarr-sma:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "3011:8989"
    networks:
      - name: torrent
        ipv4_address: "172.16.0.5"
        aliases:
          - "sonarr"
    purge_networks: yes
    etc_hosts: "{{ extra_hosts }}"
    networks_cli_compatible: yes
    env:
      TZ: "America/Chicago"
      PUID: "125"
      PGID: "996"
    volumes:
      - "{{ library }}/TV\ Shows:/tv"
      - "{{ transmission_downloads }}/complete:/downloads"
      - "{{ sonarr }}:/config:rw"
      - "{{ sonarr }}/sickbeard:/usr/local/sma/config"
    memory: 1g 
    cpu_period: 100000
    cpu_quota: 30000
#######################################################
###################### Jackett ########################
#######################################################
- name: Jackett Container
  docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "9117:9117"
    networks:
      - name: torrent
        ipv4_address: "172.16.0.2"
        aliases:
          - "jackett"
    purge_networks: yes
    etc_hosts: "{{ extra_hosts }}"
    networks_cli_compatible: yes
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "996"
    volumes:
      - "{{ jackett }}:/config"
      - "{{ jackett_torrent_blackhole }}:/downloads"
#######################################################
################### Transmission ######################
#######################################################
- name: Transmission Container
  docker_container:
    name: transmission
    image: linuxserver/transmission:latest
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ transmission }}:/config:rw"
      - "{{ transmission_downloads }}:/storage/downloads:rw"
      - "{{ transmission_watch }}:/storage/watch"
    ports:
      - "9091:9091"
    etc_hosts: "{{ extra_hosts }}"
    networks:
      - name: torrent
        ipv4_address: "172.16.0.6"
        aliases:
          - "transmission"
    purge_networks: yes
    networks_cli_compatible: yes
    env:
      TRANSMISSION_HOME: "/config"
      TRANSMISSION_DOWNLOAD_DIR: "/storage/downloads/complete"
      TRANSMISSION_INCOMPLETE_DIR: "/storage/downloads/incomplete"
      TRANSMISSION_WATCH_DIR: "/storage/watch"
      #      TRANSMISSION_RPC_USERNAME: "{{ transmission_username }}" 
      #      TRANSMISSION_RPC_PASSWORD: "{{ transmission_password }}"
      PUID: "119"
      PGID: "995"
#######################################################
#################### Deezloader #######################
#######################################################
- name: Deezloader Container
  docker_container:
    name: deezloader
    image: bocki/deezloaderrmx
    pull: true
    volumes:
      - "{{ deezloader_downloads }}:/downloads:rw"
      - "{{ deezloader }}:/config:rw"
    etc_hosts: "{{ extra_hosts }}"
    ports:
      - "1730:1730"
    networks:
      - name: torrent
        ipv4_address: "172.16.0.7"
        aliases:
          - "deezloader"
    purge_networks: yes
    networks_cli_compatible: yes
    env:
      PUID: "120"
      PGID: "995"
#######################################################
##################### Soulseek ########################
#######################################################
- name: Soulseek Container
  docker_container:
    name: soulseek
    image: realies/soulseek
    pull: true
    volumes:
      - "{{ soulseek }}/appdata:/data/.SoulseekQt:rw"
      - "{{ soulseek_downloads }}:/data/Soulseek Downloads:rw"
      - "{{ soulseek }}/logs:/data/Soulseek Chat Logs:rw"
    etc_hosts: "{{ extra_hosts }}"
    ports:
      - "6080:6080"
    networks:
      - name: torrent
        ipv4_address: "172.16.0.8"
        aliases:
          - "soulseek"
    purge_networks: yes
    networks_cli_compatible: yes
    env:
      PUID: "121"
      PGID: "995"
      resize: "scale"
      resolution: "1280x720"
#- name: download_hub with VPN
#  tags:
#    - download_hub
#  docker_container:
#    name: download_hub
#    image: nrichman/download-hub
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
#      - "{{ download_hub }}/transmission_config:/config:rw"
#      - "{{ download_hub }}/Downloads/transmission:/storage/downloads:rw"
#      - "{{ download_hub }}/soulseek_appdata:/root/.SoulseekQt"
#      - "{{ download_hub }}/soulseek_logs:/root/Soulseek Chat Logs"
#      - "{{ download_hub }}/Downloads/soulseek:/root/Soulseek Downloads"
#      - "{{ download_hub }}/Downloads/deezloader:/downloads"
#      - "{{ download_hub }}/deezloader_config:/root/.config/Deezloader Remix/config"
#      - "{{ plex_library }}:/root/Library:ro"
#    ports:
#      - "9091:9091/tcp"
#      - "9091:9091/udp"
#      - "6080:6080"
#      - "1730:1730"
#    networks:
#      - name: torrent
#        ipv4_address: "172.16.2.2"
#        aliases:
#          - "download_hub"
#    networks_cli_compatible: yes
#    env:
#      TRANSMISSION_HOME: /config
#      TRANSMISSION_DOWNLOAD_DIR: /storage/downloads/complete
#      TRANSMISSION_INCOMPLETE_DIR: /storage/downloads/incomplete
#      TRANSMISSION_WATCH_DIR: /storage/watch
#      OPENVPN_PROVIDER: "{{ vpn_provider }}"
#      OPENVPN_USERNAME: "{{ vpn_username }}"
#      OPENVPN_PASSWORD: "{{ vpn_password }}"
#      OPENVPN_CONFIG: "{{ vpn_config }}"
#      OPENVPN_OPTS: "--redirect-gateway def1 --mssfix 1450"
#      PUID: "119"
#      PGID: "995"
#      LOCAL_NETWORK: "{{ transmission_local_network }}"
#      ENABLE_UFW: "false"
#      CREATE_TUN_DEVICE: "true"
#      TRANSMISSION_RPC_USERNAME: "{{ transmission_username }}"
#      TRANSMISSION_RPC_PASSWORD: "{{ transmission_password }}"
#    capabilities:
#      - NET_ADMIN
#    restart_policy: unless-stopped
#    memory: 1g
#    cpu_period: 100000
#    cpu_quota: 50000
#
#######################################################
#################### Healthcheck ######################
#######################################################
#- name: autoheal
#  docker_container:
#    name: autoheal
#    image: willfarrell/autoheal
#    pull: true
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    env:
#      AUTOHEAL_CONTAINER_LABEL: "all"
#    cpu_period: 100000
#    cpu_quota: 10000
