---
# Inits
- name: ensure docker and nfs-common are installed
  apt:
    pkg:
      - docker.io
      - nfs-common
    state: present
  become: yes
  tags: 
    - init


- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes
  with_items:
    - "/media"
    - "{{ library }}"
    - "{{ transmission_downloads }}"
    - "{{ deezloader_downloads }}"
    - "{{ soulseek_downloads }}"
  tags:
    - init

- name: Mount nfs
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: nfs
    opts: defaults
    state: mounted
  become: yes
  with_items:
    - {name: "{{ library }}", src: "sisko.nrichman.dev:{{ library }}"}
    - {name: "{{ transmission_downloads }}", src: "sisko.nrichman.dev:{{ transmission_downloads }}"}
    - {name: "{{ deezloader_downloads }}", src: "sisko.nrichman.dev:{{ deezloader_downloads }}"}
    - {name: "{{ soulseek_downloads }}", src: "sisko.nrichman.dev:{{ soulseek_downloads }}"}
  ignore_errors: yes
  tags:
    - run

