---
- name: Create downloads group
  group:
    gid: "{{ item.gid }}"
    name: "{{ item.name }}"
    system: yes
  become: yes
  loop:
    - {gid: 995, name: downloads}
    - {gid: 996, name: library}

- name: Create Users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    create_home: no
    system: yes
  with_items:
    - { uid: "117", name: "lidarr", group: "995", groups: ["995"] }
    - { uid: "116", name: "radarr", group: "996", groups: ["996","995"]}
    - { uid: "125", name: "sonarr", group: "996", groups: ["996","995"]}
    - { uid: "122", name: "jackett", group: "996", groups: ["996"]}
    - { uid: "119", name: "transmission", group: "995", groups: ["995"]}
    - { uid: "120", name: "deezloader", group: "995", groups: ["995"]}
    - { uid: "121", name: "soulseek", group: "995", groups: ["995"]}
  become: yes

- name: Create Lidarr/Radarr/Sonarr/Jackett Config directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ itme.group }}"
    mode: 0775
  loop:
    - { path: "{{ lidarr }}",           owner: "lidarr",        group: "downloads" }
    - { path: "{{ radarr }}",           owner: "radarr",        group: "library" }
    - { path: "{{ sonarr }}",           owner: "sonarr",        group: "library" }
    - { path: "{{ radarr }}/sickbeard", owner: "radarr",        group: "library" }
    - { path: "{{ sonarr }}/sickbeard", owner: "sonarr",        group: "library" }
    - { path: "{{ jackett }}",          owner: "jackett",       group: "downloads" }
    - { path: "{{ jackett }}",          owner: "jackett",       group: "downloads" }
    - { path: "{{ transmission }}",     owner: "transmission",  group: "downloads"  }
    - { path: "{{ deezloader }}",       owner: "deezloader",    group: "downloads"  }
    - { path: "{{ soulseek }}",         owner: "soulseek",      group: "downloads"  }
    - { path: "{{ soulseek }}/logs",    owner: "soulseek",      group: "downloads" }
    - { path: "{{ soulseek }}/appdata", owner: "soulseek",      group: "downloads" }
  become: yes
