---
- name: Create Lidarr/Radarr/Sonarr/Jackett Directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{item.owner}}"
    group: library
    mode: 0775
  with_items:
    - { path: "{{ download_hub }}/lidarr", owner: "lidarr" }
    - { path: "{{ download_hub }}/radarr", owner: "radarr" }
    - { path: "{{ download_hub }}/sonarr", owner: "sonarr" }
    - { path: "{{ download_hub }}/sickbeard", owner: "nrichman" }
    - { path: "{{ download_hub }}/sickbeard/radarr", owner: "radarr" }
    - { path: "{{ download_hub }}/sickbeard/sonarr", owner: "sonarr" }
    - { path: "{{ jackett }}", owner: "jackett" }
    - { path: "{{ jackett_torrent_blackhole }}", owner: "jackett" }
  become: yes
