
- name: prepare tasks
  import_tasks: prepare.yml
  when: init

#######################################################
###################### Plex ###########################
#######################################################
- name: plex Docker Container
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    volumes:
      - "{{ plex_config }}:/config:rw"
      - "{{ plex_library }}/Movies:/movies:rw"
      - "{{ plex_library }}/TV\ Shows:/tv:rw"
      - "{{ plex_library }}/Music:/music:ro"
      - "{{ plex_library }}/Other:/other:ro"
    network_mode: "host"
    env:
      TZ: "{{ timezone }}"
      VERSION: "docker"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 100000

#######################################################
#################### Airsonic #########################
#######################################################
- name: Airsonic Docker Container
  docker_container:
    name: airsonic
    image: airsonic/airsonic
    pull: true
    volumes:
      - "{{ airsonic_config }}/data:/airsonic/data:rw"
      - "{{ airsonic_config }}/playlists:/airsonic/playlists:rw"
      - "{{ airsonic_config }}/podcasts:/airsonic/podcasts:rw"
      - "{{ plex_library }}/Music:/airsonic/music:ro"
    ports:
      - "4040:4040"
    user: "{{ airsonic_uid }}"
    groups: ['996']
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 300000


#######################################################
#################### Jellyfin #########################
#######################################################
- name: Jellyfin Docker Container
  docker_container:
    name: jellyfin
    image: jellyfin/jellyfin
    pull: true
    volumes:
      - "{{ jellyfin_config }}/data:/config:rw"
      - "{{ plex_library }}/Music:/data/music:ro"
    ports:
      - "8096:8096"
    user: "{{ jellyfin_uid }}"
    groups: ['996']
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 300000
