
- name: plex tasks
  import_tasks: plex.yml
  tags: plex

#######################################################
###################### Plex ###########################
#######################################################
- name: plex Docker Container
  tags:
    - plex
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    volumes:
      - "{{ plex_config }}:/config:rw"
      - "{{ plex_library }}/Movies:/movies:rw"
      - "{{ plex_library }}/TV\ Shows:/tv:rw"
      - "{{ plex_library }}/Music:/music:ro"
      - "{{ plex_library }}/Other:/other:ro"
    network_mode: "host"
    env:
      TZ: "{{ timezone }}"
      VERSION: "docker"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 100000
