---
- name: Create Plex Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ plex_config }}"

- name: Create airsonic user
  user: 
    name: "{{ airsonic_user }}"
    uid: "{{ airsonic_uid }}"

- name: Create airsonic directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ airsonic_user }}"
    group: "nrichman"
    mode: "0775"
  loop:
    - "{{ airsonic_config }}"
    - "{{ airsonic_config }}/data"
    - "{{ airsonic_config }}/playlists"
    - "{{ airsonic_config }}/podcasts"

- name: Grant airsonic user access to music database
  acl:
    path: "{{ plex_library }}/Music"
    entity: "{{ airsonic_user }}"
    etype: user
    permissions: r-x
    recursive: yes
    state: present

- name: Create jellyfin user
  user: 
    name: "{{ jellyfin_user }}"
    uid: "{{ jellyfin_uid }}"

- name: Create jellyfin directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jellyfin_user }}"
    group: "nrichman"
    mode: "0775"
  loop:
    - "{{ jellyfin_config }}"
    - "{{ jellyfin_config }}/data"

- name: Grant jellyfin user access to music database
  acl:
    path: "{{ plex_library }}/Music"
    entity: "{{ jellyfin_user }}"
    etype: user
    permissions: r-x
    recursive: yes
    state: present
