

######################################################################################
#                                Main Web Services                                   #
######################################################################################
#
# This playbook has roles for the main web services, it contains the main nginx
# configuration as well as my website.
#
#######################################################
###################### NGINX ##########################
#######################################################
- name: NGINX Docker Container
  tags:
    - nginx
  docker_container:
    name: nginx
    image: nginx:latest
    pull: true
    volumes:
      - "/var/www/html:/var/www/html:ro"
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/"
        #- "/etc/nginx/modules-enabled-docker:/etc/nginx/modules-enabled"
      - "/etc/ssl/nrichman.dev:/etc/ssl/nrichman.dev:ro"
        #- "/usr/share/nginx/modules:/etc/nginx/modules:ro"
      - "/var/log/nginx:/var/log/nginx:rw"
    ports:
      - "80:80"
      - "443:443"
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 25000
#######################################################
################### nrichman.dev ######################
#######################################################
- name: nrichman.dev docker
  docker_container: 
    name: nrichman.dev
    image: nrichman2/nrichman.dev
    pull: true
    ports:
      - "8080:3000"
    volumes:
      - "/home/nrichman/web/nrichman.dev/public:/opt/nrichman.dev/public:ro"
