
######################################################################################
#                                 Create Folders                                     #
######################################################################################
- name: plex tasks
  import_tasks: plex.yml
  tags: plex

- name: gitea tasks
  import_tasks: gitea.yml
  tags: gitea

#- name: nextcloud tasks
#  import_tasks: nextcloud.yml
#  tags: nextcloud

######################################################################################
#                                 Docker Networks                                    #
######################################################################################
- name: Docker main network
  tags:
    - networks
  docker_network:
    name: main
    driver: bridge
    driver_options:
      com.docker.network.bridge.name: "docker1"
    ipam_config:
      - subnet: 172.16.100.0/26
        gateway: 172.16.100.1


- name: Docker nginx isolation network
  tags:
    - networks
    - nginx
  docker_network:
    name: nginx
    driver: bridge
    driver_options: 
      com.docker.network.bridge.name: "docker4"
    ipam_config:
      - subnet: 172.16.200.0/28
        gateway: 172.16.200.1
      

######################################################################################
#                                 Docker Containers                                  #
######################################################################################
#
#
#
#
#######################################################
###################### Plex ###########################
#######################################################
- name: plex Docker Container
  tags:
    - plex
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    volumes:
      - "{{ plex_config }}:/config:rw"
      - "{{ plex_library }}/Movies:/movies:rw"
      - "{{ plex_library }}/TV\ Shows:/tv:rw"
      - "{{ plex_library }}/Music:/music:ro"
      - "{{ plex_library }}/Other:/other:ro"
    network_mode: "host"
    env:
      TZ: "{{ timezone }}"
      VERSION: "docker"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 100000
#######################################################
###################### NGINX ##########################
#######################################################
- name: NGINX Docker Container
  tags:
    - nginx
  docker_container:
    name: nginx
    image: nginx:latest
    pull: true
    volumes:
      - "/var/www/html:/var/www/html:ro"
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/nginx/sites-available/nrichman.dev:/etc/nginx/sites-enabled/nrichman.dev"
        #- "/etc/nginx/modules-enabled-docker:/etc/nginx/modules-enabled"
      - "/etc/ssl/nrichman.dev:/etc/ssl/nrichman.dev:ro"
        #- "/usr/share/nginx/modules:/etc/nginx/modules:ro"
      - "/var/log/nginx:/var/log/nginx:rw"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: nginx
        ipv4_address: "172.16.200.2"
        aliases:
          - "nginx"
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    memory: 1g
    cpu_period: 100000
    cpu_quota: 25000
#######################################################
####################### Gitea #########################
#######################################################
- name: Gitea docker image
  docker_container:
    name: gitea
    image: gitea/gitea
    pull: true
    hostname: git.nrichman.dev
    volumes:
      - "{{ gitea }}:/data:rw"
    ports:
      - "28000:3000"
    networks:
      - name: main
        ipv4_address: "172.16.100.2"
        aliases:
          - "git"
    networks_cli_compatible: yes
    restart_policy: unless-stopped
    memory: 1g
#######################################################
################### nrichman.dev ######################
#######################################################
- name: nrichman.dev docker
  docker_container: 
    name: nrichman.dev
    image: nrichman2/nrichman.dev
    ports:
      - "8080:3000"
    
