- name: Make Telegraf Dir
  file:
    path: "{{ telegraf  }}"
    state: directory
  become: yes

- name: Template Telegraf Slave
  template:
    src: "../templates/telegraf-slave.j2"
    dest: "{{ telegraf }}/telegraf.conf"
    owner: root
  become: yes

- name: Telegraf docker
  docker_container:
    name: telegraf
    image: telegraf
    pull: true
    volumes:
      - "{{ telegraf }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "161:161"
    restart_policy: unless-stopped
    memory: 1g
    dns_servers:
      - 10.0.1.6
    cpu_period: 100000
    cpu_quota: 25000

