---

# Start telegraf on all collecting hosts
- hosts: data_slave
  roles:
    - common
  tags:
    - slave

#Start telegraf (with snmp agent collection),
# influxdb and grafana on master
- hosts: data_master
  roles:
    - data
  tags:
    - master

