#Jackett, Radarr, Sonarr, Lidarr, transmission
jackett: /docker/Jackett
jackett_torrent_blackhole: /media/download_hub/Downloads/jackett
radarr: /docker/radarr
sonarr: /docker/sonarr
lidarr: /docker/lidarr
transmission: /docker/transmission
deezloader: /docker/deezloader
soulseek: /docker/soulseek

download_hub: /media/download_hub


#Radarr
radarr_output: /movies
sonarr_output: /tv

# File mounts
library: /media/Library
transmission_downloads: /media/download_hub/Downloads/transmission
soulseek_downloads: /media/Soulseek/Downloads
deezloader_downloads: /media/Deezloader
