#Jackett, Radarr, Sonarr, Lidarr, transmission
jackett: /docker/Jackett
jackett_torrent_blackhole: /media/download_hub/Downloads/jackett
radarr: /docker/radarr
sonarr: /docker/sonarr
lidarr: /docker/lidarr
transmission: /docker/transmission

download_hub: /media/download_hub

#Soulseek
soulseek: /docker/Soulseek
soulseek_downloads: /media/Soulseek

#Deezloader
deezloader_config: /docker/deezloader
deezloader_downloads: /media/Deezloader

#Radarr
radarr_output: /movies
sonarr_output: /tv

# File mounts
library_guest: /media/library
library_host: /media/Library
transmission_guest: /media/transmission
transmission_host: /media/download_hub/Downloads/transmission
